### ISSUE TITLE
Archivist config panel not accessible

### ISSUE THREAD

**Issue by aarontrom** [YunoHost-Apps/archivist_ynh#45]
### Describe the bug

YunoHost encountered an internal error when trying to access the config-panel pf archivist.

### Context

- Hardware: VPS bought online
- YunoHost version: 4.3.6.2 
- I have access to my server: Through SSH + through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using package version/branch: 1.3.2~ynh1

### Steps to reproduce

- When trying to access the config-panel in archivist I get the following error message:

` Config panel question 'encrypt' should be initialized with a value during install or upgrade.`

- I did the following:
   1. Go to: mywebsite/yunohost/admin/#/apps/archivist
   2. Click on "config-panel"
   3. See this error:

![archivist config panel](https://user-images.githubusercontent.com/69819346/151027825-7d490a70-067f-4ad3-9869-38064c08f9ec.jpg)

**Comment by yalh76** [comment]
should be fixed for now

**Comment by pjpmosteiro** [comment]
Same issue here. 
Yunohost 11.0.9.14 stable
Archivist version  1.3.3~ynh1

**Comment by Xia0ben** [comment]
Hello, got this same issue today, would there happen to a hotfix to be applied ? =)

**Comment by Mauskill2** [comment]
Hello, i got this issue too today :-(

**Comment by lapineige** [comment]
Same here.
I don't know where to check for this value.

Is this related to packaging v2 @maniackcrudelis ?

**Comment by lapineige** [comment]
I tried with a fresh install, encryption enabled or not, password set up or not, same issue.
Yet the `encrypt` is the one we setup with the "Do you want to encrypt your backups ?" question. I don't see any syntax issue here.

**Comment by maniackcrudelis** [comment]
I'm not working on packaging anymore, and so I didn't follow the v2 changelog.
I'm only working on the upstream app when needed.

**Comment by lapineige** [comment]
Ok so it's unrelated.
It's very strange anyway, the value is set during install, why does it fails with such an error… :thinking:

(May I propose a v2 version of this app ?)

**Comment by lapineige** [comment]
First, I need to understand it… and I really don't see why it's happening :(

**Comment by CodeShakingSheep** [comment]
Just wanted to report that I encounter this error too. Anybody working on this?
![image](https://github.com/YunoHost-Apps/archivist_ynh/assets/19874562/4efd84c0-8269-4361-bac9-bf70bccf59e6)

**Comment by Dazeilad** [comment]
Same here : 
![image](https://github.com/YunoHost-Apps/archivist_ynh/assets/64801705/ed2939ac-a251-4e2c-962c-da557fd03135)

**Comment by umrath** [comment]
The problem is still there.
(just to avoid this from getting closed without being fixed.)

**Comment by csolisr** [comment]
[As a matter of fact, the CI marked the application as not working due to a related issue](https://ci-apps.yunohost.org/ci/job/17370):

```
124  WARNING Unknown key 'name' found in config panel
279  WARNING Traceback (most recent call last):
279  WARNING   File "<stdin>", line 5, in <module>
279  WARNING AssertionError: Setting file /etc/yunohost/apps//settings.yml does not exists ?
280  WARNING grep: /Backup_list.conf: No such file or directory
284  WARNING cat: /passkey: No such file or directory
288  WARNING grep: /Backup_list.conf: No such file or directory
293  WARNING grep: /Backup_list.conf: No such file or directory
298  WARNING grep: /Backup_list.conf: No such file or directory
302  WARNING grep: /Backup_list.conf: No such file or directory
306  WARNING grep: /etc/yunohost/apps//settings.yml: No such file or directory
312  WARNING grep: /Backup_list.conf: No such file or directory
386  WARNING Traceback (most recent call last):
387  WARNING   File "<stdin>", line 5, in <module>
388  WARNING AssertionError: Setting file /etc/yunohost/apps/overwrite_cron/settings.yml does not exists ?
469  WARNING Traceback (most recent call last):
470  WARNING   File "<stdin>", line 5, in <module>
470  WARNING AssertionError: Setting file /etc/yunohost/apps/admin_mail_html/settings.yml does not exists ?
1497 ERROR Config panel question 'encrypt' should be initialized with a value during install or upgrade.
Peak RAM usage during this test: 131MB
RAM usage diff after test: 11MB

--- FAIL ---

Working time for this test: 1 minute, 14 seconds (01:04:20)
```
